#%RAML 1.0
title: Sharpy JSON
version: 0
documentation:
  - title: Sharpy JSON
    content: |
      API v0 JSON API examples can be found here

/auth:
  description: Registration & authorization 

  /login:
    get:
      responses:
        200:
          body:
            application/json:
                type: |
                  {
                    "type": 1, // Login
                    "data": {
                      "login": "username",
                      "pass": "password"
                    }
                  }
                example: |
                  {
                    "type": 1,
                    "code": 1, // Success
                    "data": {
                      "token": "42b07d383c334",
                      "userId": 2
                    }
                  }
  /logout:
    get:
      responses:
        200:
          body:
            application/json:
                type: |
                  {
                    "type": 2, // Logout
                    "data": {
                      "token": "42b07d383c334",
                      "userId": 2
                    }
                  }
                example: |
                  {
                    "type": 2,
                    "code": 1, // Success
                  }
  /register:
    get:
      responses:
        200:
          body:
            application/json:
                type: |
                  {
                    "type": 3, // Register
                    "data": {
                      "login": "testuser",
                      "pass": "strongPass",
                      "email": "testemail@domain.com"
                    }
                  }
                example: |
                  {
                    "type": 3,
                    "code": 1, // Success
                  }
