#%RAML 1.0
title: Sharpy JSON # required title
version: 0
documentation:
  - title: Description2
    content: |
      API v0 JSON API examples can be found here

/auth:
  description: Registration & authorization 

  /login:
    get:
      responses:
        200:
          body:
            application/json:
                type: |
                  {
                    "command": 1, // Login
                    "data": {
                      "login": "username",
                      "password": "password"
                    }
                  }
                example: |
                  {
                    "command": 1,
                    "status": 1, // Success
                    "data": {
                      "token": "42b07d383c334"
                    }
                  }

  /logout:
    get:
      responses:
        200:
          body:
            application/json:
                type: |
                  {
                    "command": 2, // LogOut
                    "data": {
                      "token": "42b07d383c334",
                    }
                  }
                example: |
                  {
                    "command": 2,
                    "status": 1, // Success
                  }
